# Reusable secret scan with gitleaks over full git history.
# Picks up the caller repo's .gitleaks.toml at the repo root automatically.
# Caller permissions: contents: read.
# Secrets: GITLEAKS_LICENSE (optional; only needed for org-owned repos).
# Example caller: templates/workflows/gitleaks.yaml
name: Gitleaks

on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
        required: false

permissions:
  contents: read

jobs:
  gitleaks:
    name: Detect secrets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
